In [7]:
import numpy as np
import random

In [9]:
movie_id = np.arange(1301, 2301)
print(movie_id[:10]) #shows the first 10 el
print(movie_id.size) #shows size

[1301 1302 1303 1304 1305 1306 1307 1308 1309 1310]
1000


In [10]:
arr = np.empty([2, 2], dtype = complex)
print(arr)

arr = np.full((2, 3), 5)
print(arr)

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
[[5 5 5]
 [5 5 5]]


In [4]:
arr = np.zeros([2, 3])
print(arr)

arr = np.ones([2, 3])
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.vstack((A, B))

print(C)

[[1 2 3]
 [4 5 6]]


In [8]:
movie_matrix = []
for user in range(100):
    movies_rated_by_me = np.full(1000, -1)
    num_movies_rated = random.randint(0, 999)
    movies_that_i_will_rate = random.sample(range(0, 1000), num_movies_rated)
    for index in movies_that_i_will_rate:
        movies_rated_by_me[index] = random.randint(0, 10)
    movie_matrix.append(movies_rated_by_me)

movie_matrix = np.array(movie_matrix)
print(movie_matrix)
print('Shape of the array:', movie_matrix.shape)

[[ 0  9  3 ...  4  4  6]
 [-1  8  4 ...  3 10 10]
 [ 5  7  3 ...  4  3 -1]
 ...
 [-1  5 10 ... -1 -1 -1]
 [-1 -1 -1 ...  5  3 -1]
 [ 9  8 -1 ... -1 -1  2]]
Shape of the array: (100, 1000)
