In [ ]:
import numpy as np

#Python list example
python_list = [1, 2, 3, 4]
python_result = [x * 2 for x in python_list]

#Numpy list example
numpy_list = np.array([1, 2, 3, 4])
numpy_result = numpy_list * 2

print(python_result)
print(numpy_result)

[2, 4, 6, 8]
[np.int64(2), np.int64(4), np.int64(6), np.int64(8)]


In [3]:
# 2D array
two_d_array = np.array([[1, 2, 3], [1, 2 ,3]])
print(two_d_array)

[[1 2 3]
 [1 2 3]]


In [4]:
#Example with addition

array = np.array([1, 2, 3])
array = array + 3
print(array)

[4 5 6]


In [5]:
# Example with math function
arr = np.array([1, 2, 3, 4])
print(f'sum = {np.sum(arr)}')
print(f'mean = {np.mean(arr)}')
print(f'standart deviation = {np.std(arr)}')

sum = 10
mean = 2.5
standart deviation = 1.118033988749895


In [7]:
#Matrix multiplication
matrix_1 = np.array([[1 , 2], [2, 3]])
matrix_2 = np.array([[1, 2], [2, 3]])
result = np.dot(matrix_1, matrix_2)
print(result)

[[ 5  8]
 [ 8 13]]
